keystore:   
  keyPassword: "![oglK0vv+lop10jrBthtdrQ==]"
  password: "![oglK0vv+lop10jrBthtdrQ==]"
          
address:   
  clientId: "![VRZ/n8rwmYWq+oMh9vmmnSQHV5ef7lh/F59/c9Z6wWEwnJaoP8WTQf/1d/7IeMwF]"
  clientSecret: "![fQcWXyydBf2+85bOFHvkoxEj0g049BVa0mdKqVZrOl5lrHHS1vHX2k+1O2kVpPTO]"
